In [39]:

from pandas import  *
from numpy import *
from seaborn import *
from matplotlib.pyplot import *
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler


In [40]:
df=read_csv('NFLX.csv')

In [41]:
df.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')

In [42]:
df=df.drop(columns='Date')

In [43]:
x=df.drop(columns='Close')

In [44]:
x.columns


Index(['Open', 'High', 'Low', 'Adj Close', 'Volume'], dtype='object')

In [45]:
y=df[['Close']]

RF

In [46]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [47]:
from sklearn.ensemble import RandomForestRegressor
r=RandomForestRegressor(n_estimators=100)
r.fit(x_train,y_train)

c:\Users\debna\anaconda3\Lib\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestRegressor()

In [48]:
r.score(x_train,y_train)

0.9999761960719327

In [49]:
r.score(x_test,y_test)

0.9997538761441715

In [50]:
r.predict([[262.00,267.894,250.029,254.255,11896100]])

c:\Users\debna\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([255.63222964])

254 is accurate

DT

In [51]:
from sklearn.tree import  DecisionTreeRegressor
d=DecisionTreeRegressor()
d.fit(x_train,y_train)

DecisionTreeRegressor()

In [52]:
d.score(x_train,y_train)

1.0

In [53]:
d.score(x_test,y_test)

0.9996512800550738

In [54]:
d.predict([[262.00,267.894,250.029,254.255,11896100]])

c:\Users\debna\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


array([254.255])

Accurate !

Now, ET

In [55]:
'''from sklearn.ensemble import ExtraTreesRegressor
e=ExtraTreesRegressor(n_estimators=100)
e.fit(x_train,y_train)'''

'from sklearn.ensemble import ExtraTreesRegressor\ne=ExtraTreesRegressor(n_estimators=100)\ne.fit(x_train,y_train)'

In [56]:
import joblib
#loading The models anywhere

e=joblib.load('Netflix Stocks ET.pkl')

In [57]:
e.score(x_train,y_train)

1.0

In [58]:
e.score(x_test,y_test)

0.99979915998362

In [59]:
#saving The Models

#joblib.dump(e,'Netflix Stocks ET.pkl')


In [60]:
e.predict([[262.00,267.894,250.029,254.255,11896100]])

c:\Users\debna\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but ExtraTreesRegressor was fitted with feature names
  warnings.warn(


array([254.255])

Accurate!

Gradient Boost

In [61]:
from sklearn.ensemble import GradientBoostingRegressor
g=GradientBoostingRegressor(n_estimators=100)
g.fit(x_train,y_train)

c:\Users\debna\anaconda3\Lib\site-packages\sklearn\ensemble\_gb.py:668: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?


GradientBoostingRegressor()

In [62]:
g.score(x_train,y_train)

0.9999679106657974

In [63]:
g.score(x_test,y_test)

0.9997562114211478

In [64]:
g.predict([[262.00,267.894,250.029,254.255,11896100]])

c:\Users\debna\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but GradientBoostingRegressor was fitted with feature names
  warnings.warn(


array([254.45724632])

Catboost 

In [65]:
from catboost import  CatBoostRegressor,CatBoostClassifier

In [66]:
c=CatBoostRegressor(learning_rate=1,n_estimators=1000)
c.fit(x_train,y_train)

0:	learn: 22.7143915	total: 5.29ms	remaining: 5.28s
1:	learn: 17.7002354	total: 8.27ms	remaining: 4.13s
2:	learn: 16.2381256	total: 10.2ms	remaining: 3.38s
3:	learn: 14.6976261	total: 12ms	remaining: 2.98s
4:	learn: 11.5299072	total: 13.3ms	remaining: 2.64s
5:	learn: 10.3233681	total: 14.5ms	remaining: 2.4s
6:	learn: 10.0116994	total: 15.7ms	remaining: 2.23s
7:	learn: 9.0302567	total: 17.2ms	remaining: 2.13s
8:	learn: 8.7393070	total: 18.6ms	remaining: 2.05s
9:	learn: 8.0928051	total: 19.9ms	remaining: 1.97s
10:	learn: 7.9543469	total: 21.3ms	remaining: 1.92s
11:	learn: 7.4808230	total: 22.8ms	remaining: 1.87s
12:	learn: 6.4414749	total: 24.4ms	remaining: 1.85s
13:	learn: 6.2897175	total: 25.7ms	remaining: 1.81s
14:	learn: 5.7385524	total: 26.7ms	remaining: 1.76s
15:	learn: 5.4903335	total: 27.8ms	remaining: 1.71s
16:	learn: 5.3257477	total: 28.9ms	remaining: 1.67s
17:	learn: 5.2001654	total: 30.3ms	remaining: 1.65s
18:	learn: 4.8858325	total: 31.8ms	remaining: 1.64s
19:	learn: 4.60997

In [67]:
c.score(x_train,y_train)

0.9999999999947741

In [68]:
c.score(x_test,y_test)

0.9962603686341682

In [69]:
c.predict([[262.00,267.894,250.029,254.255,11896100]])

array([254.25494071])

LGBM

In [70]:
from  lightgbm import *

In [71]:
# Initialize the LightGBM classifier
l = LGBMRegressor(n_estimators=1000, learning_rate=1)
l.fit(x_train, y_train)


[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004719 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1180
[LightGBM] [Info] Number of data points in the train set: 706, number of used features: 5
[LightGBM] [Info] Start training from score 416.138769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive g

LGBMRegressor(learning_rate=1, n_estimators=1000)

In [72]:
l.score(x_train,y_train)

0.9998128692869234

In [73]:
l.score(x_test,y_test)

0.9966843605017052

In [74]:
l.predict([[262.00,267.894,250.029,254.255,11896100]])

array([254.25566577])

Accurate !

RF < GB < DT = ET = CAT  = LGBM